#!/bin/bash

docker run -it -d --name syzploit\
  -u 1000:1000 \
  --network=host \
  --device=/dev/kvm \
  --group-add $(getent group kvm | cut -d: -f3) \
  -v "$(pwd):/workspace/syzploit" \
  syzploit-env