// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_mmap
#define __NR_mmap 222
#endif
#ifndef __NR_sendmsg
#define __NR_sendmsg 211
#endif
#ifndef __NR_socket
#define __NR_socket 198
#endif

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
		syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul, /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/7ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	const char* reason;
	(void)reason;
				intptr_t res = 0;
	if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {}
	res = syscall(__NR_socket, /*domain=*/0x10ul, /*type=*/3ul, /*proto=*/0);
	if (res != -1)
		r[0] = res;
*(uint64_t*)0x20000300 = 0;
*(uint32_t*)0x20000308 = 0x400300;
*(uint64_t*)0x20000310 = 0x200002c0;
*(uint64_t*)0x200002c0 = 0x20001280;
*(uint32_t*)0x20001280 = 0;
*(uint16_t*)0x20001284 = 0x24;
*(uint16_t*)0x20001286 = 0;
*(uint32_t*)0x20001288 = 0;
*(uint32_t*)0x2000128c = 0;
*(uint8_t*)0x20001290 = 0;
*(uint8_t*)0x20001291 = 0;
*(uint16_t*)0x20001292 = 0;
*(uint32_t*)0x20001294 = 0;
*(uint16_t*)0x20001298 = 0;
*(uint16_t*)0x2000129a = 0;
*(uint16_t*)0x2000129c = 0;
*(uint16_t*)0x2000129e = 0;
*(uint16_t*)0x200012a0 = 0;
*(uint16_t*)0x200012a2 = 0;
*(uint64_t*)0x200002c8 = 0xe98;
*(uint64_t*)0x20000318 = 1;
*(uint64_t*)0x20000320 = 0;
*(uint64_t*)0x20000328 = 0;
*(uint32_t*)0x20000330 = 0;
	syscall(__NR_sendmsg, /*fd=*/r[0], /*msg=*/0x20000300ul, /*f=*/0ul);
	return 0;
}
