[project]
name = "kexploit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "capstone>=5.0.6",
    "keystone-engine>=0.9.2",
    "openai>=1.82.1",
    "pycparser>=2.22",
    "pydantic>=2.11.5",
    "pyelftools>=0.32",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
    "typer>=0.16.0",
]

[tool.uv]
package = true

[project.scripts]
kexploit = "kexploit.main:main"
