[project]
name = "kexploit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.82.1",
    "pycparser>=2.22",
    "pyelftools>=0.32",
    "python-dotenv>=1.1.0",
    "typer>=0.16.0",
]
