// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE 

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#ifndef __NR_add_key
#define __NR_add_key 217
#endif
#ifndef __NR_mmap
#define __NR_mmap 222
#endif

uint64_t r[1] = {0x0};

int main(void)
{
		syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul, /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/7ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul, /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/0x32ul, /*fd=*/(intptr_t)-1, /*offset=*/0ul);
	const char* reason;
	(void)reason;
				intptr_t res = 0;
	if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {}
memcpy((void*)0x20000000, "keyring\000", 8);
memcpy((void*)0x20000840, "syz", 3);
*(uint8_t*)0x20000843 = 0x21;
*(uint8_t*)0x20000844 = 0;
	res = syscall(__NR_add_key, /*type=*/0x20000000ul, /*desc=*/0x20000840ul, /*payload=*/0ul, /*paylen=*/0ul, /*keyring=*/0xfffffffb);
	if (res != -1)
		r[0] = res;
memcpy((void*)0x200003c0, "dns_resolver\000", 13);
memcpy((void*)0x20000080, "\x00\x00\x01\x02", 4);
	syscall(__NR_add_key, /*type=*/0x200003c0ul, /*desc=*/0ul, /*payload=*/0x20000080ul, /*paylen=*/4ul, /*keyring=*/r[0]);
	return 0;
}
